name: Android CI/CD

on: 

  push:
    branches: [develop]
  pull_request:
    branches: [master]
  jobs:
    build: 

      runs: ubuntu-latest

      steps: 
      - uses: checkout@v2
      - name: Set up JDK 1.8
      uses: action/set-up-java@v1
      with:
        java-version: 1.8
      - name: Build with gradle
      run: ./gradleview/build
      - name: Upload APK
      uses: upload-artifact@3.1
      with:
      name: app
      path: app/build/outputs/apk/debug/app-debug.apk
