name: Android CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
     
  build-dev-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Download legacy Android SDK Tools
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/tools_r25.2.5-linux.zip -O tools_r25.2.5-linux.zip
          unzip -q tools_r25.2.5-linux.zip -d $HOME/android-sdk
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/tools:$HOME/android-sdk/tools/bin:$PATH" >> $GITHUB_ENV
          sdkmanager "platforms;android-23" "build-tools;23.0.3"
  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app
      #     path: app/build/outputs/apk/debug/app-debug.apk
